### ISSUE TITLE
Trying to create a platform view of unregistered type: chavesgu/scan_view

### ISSUE THREAD

**Issue by Dev-Autoly** [chavesgu/FlutterScan#1]
Getting this Error after adding firebase to pubspec

**Comment by chavesgu** [comment]
> Getting this Error after adding firebase to pubspec

what's your flutter version?
please show your `flutter doctor -v`

**Comment by Dev-Autoly** [comment]
I get error after adding **flutter_facebook_auth: "^0.3.0"**, 
It works if i remove this plugin



[√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19041.572], locale en-IN)
    • Flutter version 1.22.3 at C:\flutter
    • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Farhan_HP\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.51.0)
    • VS Code at C:\Users\Farhan_HP\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.16.0

[√] Connected device (1 available)
    • SM G970W (mobile) • R58MB2REWTX • android-arm64 • Android 10 (API 29)

• No issues found!


--------------ERROR---------------------
E/flutter (30048): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: chavesgu/scan_view
E/flutter (30048): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:192)
E/flutter (30048): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/flutter (30048): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter (30048): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/flutter (30048): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter (30048): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter (30048): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (30048): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (30048): 	at android.os.Looper.loop(Looper.java:197)
E/flutter (30048): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
E/flutter (30048): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (30048): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
E/flutter (30048): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
E/flutter (30048): , null, null)
E/flutter (30048): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (30048): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (30048): <asynchronous suspension>
E/flutter (30048): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (30048): #3      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039:54)
E/flutter (30048): #4      AndroidViewController.create (package:flutter/src/services/platform_views.dart:749:11)
E/flutter (30048): #5      TextureAndroidViewController.create (package:flutter/src/services/platform_views.dart:1018:34)
E/flutter (30048): #6      TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1002:14)
E/flutter (30048): #7      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (30048): #8      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (30048): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1756:9)
E/flutter (30048): #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (30048): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (30048): #12     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:560:15)
E/flutter (30048): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (30048): #14     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
E/flutter (30048): #15     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:498:7)
E/flutter (30048): #16     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
E/flutter (30048): #17     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:402:14)
E/flutter (30048): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (30048): #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (30048): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (30048): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (30048): #22     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1308:11)
E/flutter (30048): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (30048): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (30048): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (30048): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (30048): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
E/flutter (30048): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
E/flutter (30048): #29     RenderObject.layout (package:flutter/src/renderin

**Comment by chavesgu** [comment]
> I get error after adding **flutter_facebook_auth: "^0.3.0"**,
> It works if i remove this plugin
> 
> [√] Flutter (Channel stable, 1.22.3, on Microsoft Windows [Version 10.0.19041.572], locale en-IN)
> • Flutter version 1.22.3 at C:\flutter
> • Framework revision 8874f21e79 (2 weeks ago), 2020-10-29 14:14:35 -0700
> • Engine revision a1440ca392
> • Dart version 2.10.3
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> • Android SDK at C:\Users\Farhan_HP\AppData\Local\Android\sdk
> • Platform android-30, build-tools 29.0.3
> • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> • All Android licenses accepted.
> 
> [√] Android Studio (version 3.6)
> • Android Studio at C:\Program Files\Android\Android Studio
> • Flutter plugin version 49.0.1
> • Dart plugin version 192.8052
> • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] VS Code (version 1.51.0)
> • VS Code at C:\Users\Farhan_HP\AppData\Local\Programs\Microsoft VS Code
> • Flutter extension version 3.16.0
> 
> [√] Connected device (1 available)
> • SM G970W (mobile) • R58MB2REWTX • android-arm64 • Android 10 (API 29)
> 
> • No issues found!
> 
> --------------ERROR---------------------
> E/flutter (30048): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: chavesgu/scan_view
> E/flutter (30048): at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:192)
> E/flutter (30048): at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
> E/flutter (30048): at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
> E/flutter (30048): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
> E/flutter (30048): at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
> E/flutter (30048): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
> E/flutter (30048): at android.os.MessageQueue.nativePollOnce(Native Method)
> E/flutter (30048): at android.os.MessageQueue.next(MessageQueue.java:336)
> E/flutter (30048): at android.os.Looper.loop(Looper.java:197)
> E/flutter (30048): at android.app.ActivityThread.main(ActivityThread.java:8167)
> E/flutter (30048): at java.lang.reflect.Method.invoke(Native Method)
> E/flutter (30048): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
> E/flutter (30048): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
> E/flutter (30048): , null, null)
> E/flutter (30048): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
> E/flutter (30048): #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
> E/flutter (30048):
> E/flutter (30048): #2 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
> E/flutter (30048): #3 TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1039:54)
> E/flutter (30048): #4 AndroidViewController.create (package:flutter/src/services/platform_views.dart:749:11)
> E/flutter (30048): #5 TextureAndroidViewController.create (package:flutter/src/services/platform_views.dart:1018:34)
> E/flutter (30048): #6 TextureAndroidViewController.setSize (package:flutter/src/services/platform_views.dart:1002:14)
> E/flutter (30048): #7 RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
> E/flutter (30048): #8 RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
> E/flutter (30048): #9 RenderObject.layout (package:flutter/src/rendering/object.dart:1756:9)
> E/flutter (30048): #10 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
> E/flutter (30048): #11 RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
> E/flutter (30048): #12 RenderStack.performLayout (package:flutter/src/rendering/stack.dart:560:15)
> E/flutter (30048): #13 RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
> E/flutter (30048): #14 MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:12)
> E/flutter (30048): #15 _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:498:7)
> E/flutter (30048): #16 MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:243:7)
> E/flutter (30048): #17 RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:402:14)
> E/flutter (30048): #18 RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
> E/flutter (30048): #19 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
> E/flutter (30048): #20 RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
> E/flutter (30048): #21 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
> E/flutter (30048): #22 _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1308:11)
> E/flutter (30048): #23 RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
> E/flutter (30048): #24 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
> E/flutter (30048): #25 RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
> E/flutter (30048): #26 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
> E/flutter (30048): #27 RenderObject.layout (package:flutter/src/rendering/object.dart:1777:7)
> E/flutter (30048): #28 RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:14)
> E/flutter (30048): #29 RenderObject.layout (package:flutter/src/renderin

I add the plugin you said, It works well.
Did you add
```xml
<meta-data
            android:name="flutterEmbedding"
            android:value="2" />
```
in your `androidManifest.xml`?

**Comment by Dev-Autoly** [comment]
I am using following plugins from firebase, I get this issue only if I add flutter_facebook_auth plugin, Otherwise its works as expected, 

Yes, meta-data u mentioned is in android Manifest

  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  google_sign_in: ^4.5.6
  cloud_firestore: ^0.14.3
#  flutter_facebook_auth: "^0.3.0"
  firebase_messaging: "^8.0.0-dev.8"

**Comment by chavesgu** [comment]
> I am using following plugins from firebase, I get this issue only if I add flutter_facebook_auth plugin, Otherwise its works as expected,
> 
> Yes, meta-data u mentioned is in android Manifest
> 
> firebase_core: ^0.5.2
> firebase_auth: ^0.18.3
> google_sign_in: ^4.5.6
> cloud_firestore: ^0.14.3
> 
> # flutter_facebook_auth: "^0.3.0"
> firebase_messaging: "^8.0.0-dev.8"

I‘m sorry that I can't recurrent this bug,
I think you can just run example to test and create a new project to test

**Comment by chavesgu** [comment]
you can follow this [https://github.com/flutter/flutter/issues/78831](https://github.com/flutter/flutter/issues/78831)
