### ISSUE TITLE
貌似有一直在后台运行的bug,是不是没有dispose?

### ISSUE THREAD

**Issue by xuwankang** [chavesgu/FlutterScan#4]
E/Camera_APM : (17023): [APM]APM's Thread is started
E/Camera_APM : (17023): [APM] This app is forground app
D/CameraInstance(17023): Opening camera
E/Camera  (17023): Error 2
I/chatty  (17023): uid=10345 CameraThread identical 8 lines
E/Camera  (17023): Error 2

系统也提示app在后台使用相机

**Comment by chavesgu** [comment]
调用pause方法

**Comment by xuwankang** [comment]
> 调用pause方法
ok
